.github/workflows/test.yml

ci: 🎡 add unit test workflow

---

.gitignore
Makefile
readme.md

Implement a new build and installation process based on Makefile

chore: 🤖 add new makefile to build binary and checksum

---

Makefile
go.mod
validator.md

new PR to fix makefile issues (install + version display)
duplicates #32

chore: 🤖 fix make install + version display

---

config.yml
readme.md

added a quick access table in the first section of readme.md

Update readme.md - added quick access table 

---

validator.md

changed max validator comission in the create validator command to 50% and included a note that it cannot be changed

changed max validator comission to 50%

---

app/app.go
app/setup_handlers.go
x/incentive/types/keys.go

Fix the incentive store issue happening during upgrade

fix: 🐛 incentive store issue

---

Makefile

REF:  https://github.com/elys-network/elys/pull/107
After much headache, reseting the repo/head and all that stupid jazz. :D  I was able to resolve the issue.
```
elys@artorias:~/effofxprime-elys$ git pull
Updating 3d621ae..8dafdb7
Fast-forward
Makefile | 27 +++++++++++++++++++++++++--
1 file changed, 25 insertions(+), 2 deletions(-)
elys@artorias:~/effofxprime-elys$ make build
Current Go version: 1.20
--> Make sure that the dependencies haven't been altered.
^Cmake: *** [Makefile:99: go.sum] Interrupt
```
I did a ctrl-c to stop the rest of the build.  No more fatal names error.  This was coming from the Makefile that issues a `git describe --tags .....` check.
I am completely stumped as to why it was happening before and not now.
```
elys@artorias:~/effofxprime-elys$ git describe
fatal: …
```

Resubmit of updated Makefile

---

app/test_setup.go
config.yml
x/amm/types/query.pb.gw.go
x/assetprofile/types/query.pb.gw.go
x/burner/types/query.pb.gw.go
x/commitment/types/query.pb.gw.go
x/epochs/types/query.pb.gw.go
x/incentive/keeper/keeper.go
x/incentive/keeper/keeper_fees.go
x/incentive/keeper/keeper_fees_test.go
x/incentive/keeper/keeper_liquidity.go
x/incentive/keeper/keeper_lps.go
x/incentive/keeper/keeper_lps_test.go
x/incentive/keeper/keeper_shares_test.go
x/incentive/keeper/keeper_stakers_test.go
x/incentive/keeper/keeper_test.go
x/incentive/keeper/keeper_withdraw_test.go
x/incentive/keeper/params.go
x/incentive/types/params.go
x/incentive/types/params_test.go
x/incentive/types/query.pb.gw.go
x/liquidityprovider/types/query.pb.gw.go
x/oracle/keeper/price_feeder_test.go
x/oracle/types/query.pb.gw.go
x/parameter/types/query.pb.gw.go
x/tokenomics/types/query.pb.gw.go

- add unit tests on lps and stakers reward distribution
- add unit tests on gas fees collection
- add unit tests on share calculation and delegation amount calculation
- add unit tests on incentive parameter validation check and fix error with parameter load/commit

feat: add unit test on lps and stakers reward distribution part

---

x/amm/keeper/msg_server_swap_exact_amount_in_test.go
x/amm/keeper/msg_server_swap_exact_amount_out_test.go
x/amm/keeper/route_exact_amount_in_test.go
x/amm/keeper/route_exact_amount_out_test.go

- Fix pointer issue with amm unit testing files.
- Fix some value in unit testing to show converted amount to make unit testing succeed.

fix issues with pointer in amm unit test files

---

x/incentive/migrations/v3_migration.go
x/incentive/module.go

- Add a migrator for v3
- Register it

feat: add v3 migrator

---

validator.md

Added multiple gas fee option document for validators.

Add minimum gas prices setting to enable multiple gas tokens

---

x/commitment/keeper/keeper.go
x/incentive/keeper/keeper.go
x/incentive/keeper/keeper_fees.go
x/incentive/keeper/keeper_fees_test.go
x/incentive/keeper/keeper_lps.go
x/incentive/keeper/keeper_lps_test.go
x/incentive/keeper/keeper_withdraw.go
x/incentive/keeper/keeper_withdraw_test.go
x/incentive/keeper/params.go
x/incentive/types/expected_keepers.go
x/incentive/types/types.go
x/parameter/types/keys.go

- implement revenue collector
- track revenue amount
- fix USDC withdraw function

feat: implement revenue collect

---

x/margin/spec/README.md

Added basic margin spec from discussion

Add basic margin spec

---

scripts/csv/csv.ts
scripts/csv/data.csv
scripts/csv/index.ts
scripts/propose/data.csv
scripts/propose/propose.sh

- Complete bash script of submitting gov proposal for updating pool multiplier information
- Fix minor issues with csv export - added poolId, write empty string for invalid data, remove quotation, fix type conversion issue with typescript and google spread sheet.

feat: complete a bash script to submit update pool info gov proposal

---

actions/cli/Dockerfile

* Update from v0.26.1 to latest

Ignite github actions cli update

---

app/app.go
app/setup_handlers.go
go.mod
go.sum
testutil/network/network.go
x/oracle/keeper/band_request.go

Closes: #181
Some remaining changes listed in this guide https://docs.ignite.com/migration/v0.27.1#imports needed to be added along with the migration of consensus and crisis modules.
---
I have...
I have...
N/A
N/A

fix: remaining changes for 47 upgrade

---

.github/workflows/release.yml
actions/cli/Dockerfile

Closes: #179
use custom ignite-cli docker image to use latest go version 1.20 and appended --yes flag to `build` command
---
I have...
I have... …

ci: fix release process

---

app/setup_handlers.go
docs/static/openapi.yml

Closes: #182
Added missing changes to store upgrades to include both new margin and wasm modules
---
I have...
I have... …

feat: add new modules to store upgrades

---

app/setup_handlers.go

Closes: #182
the param table must be initialised manually from the `setUpgradeHandler` function
---
I have...
I have... …

fix: param table must be initialized manually

---

app/setup_handlers.go
x/margin/types/params.go

Closes: #182
Wrong key table functions were used for module param key table manual init process.
---
I have...
I have... …

fix: wrong key table used with manual init of param key tables

---

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/docs.md
.github/PULL_REQUEST_TEMPLATE/other.md

Add some changes to the description section of the PR templates to provide an example of ticket links.
---
I have...
I have... …

chore: update description section in PR templates

---

.github/workflows/release.yml

Closes:
* https://github.com/elys-network/issues/issues/286
Use ubuntu CI runner instead of self-hosted
---
I have...
I have... …

ci: use ubuntu runner

---

docs/static/openapi.yml
proto/elys/margin/pool.proto
x/margin/client/cli/query_pool_test.go
x/margin/keeper/get_amm_pool.go
x/margin/keeper/get_amm_pool_balance.go
x/margin/keeper/get_amm_pool_balance_test.go
x/margin/keeper/get_none_native_asset.go
x/margin/keeper/has_sufficient_pool_balance.go
x/margin/keeper/keeper.go
x/margin/keeper/msg_server_close.go
x/margin/keeper/msg_server_open.go
x/margin/keeper/open_long.go
x/margin/keeper/open_long_test.go
x/margin/keeper/pool_test.go
x/margin/types/expected_keepers.go
x/margin/types/mocks/open_long_checker.go
x/margin/types/pool.go
x/margin/types/pool.pb.go
x/margin/types/pool_test.go

Closes:
- https://github.com/elys-network/issues/issues/306
- Allow any denom can be used as collateral in long position.
- Make it available to work with more than 3 assets pool.
- Margin pool initiate according to its corresponding amm pool.
- Fix minor unit tests failure.
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only be …

chore: multiple asset and any denom

---

app/setup_handlers.go

Closes:
* https://github.com/elys-network/issues/issues/379
Add new module to setup handler.
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, demo videos can be highly beneficial in demonstrating …

chore: add new module to setup handler

---

x/margin/migrations/new_migrator.go
x/margin/migrations/v2_migration.go
x/margin/module.go

Closes:
* https://github.com/elys-network/issues/issues/379
Add migrator func to margin module in order to init new param `invariant check epoch`
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, …

feat: add margin migrator func

---

x/margin/keeper/get_none_native_asset_test.go
x/margin/keeper/open_long.go
x/margin/keeper/open_long_test.go
x/margin/types/expected_keepers.go
x/margin/types/mocks/open_long_checker.go

add missing test case for get non native asset 
---
I have...
I have...

test: add get-non-native-asset-test

---

config.yml

Update default margin params in `config.yml` file
---
I have...
I have...

chore: update margin params in config file

---

x/margin/keeper/begin_blocker.go
x/margin/keeper/begin_blocker_process_mtp.go
x/margin/keeper/open_long_process.go
x/margin/keeper/open_short_process.go
x/margin/keeper/open_short_test.go
x/margin/module.go
x/margin/types/expected_keepers.go
x/margin/types/mocks/open_short_checker.go

Closes:
* https://github.com/elys-network/issues/issues/390
Add additional logic for short flow
---
I have...
I have... …

feat: add additional short flow logic

---

scripts/testing/setup_localnet_nodes.sh
x/incentive/migrations/v4_migration.go
x/incentive/module.go

Fix missing incentive module migrator function.
---
I have...
I have...

fix: add missing incentive module migrator function

---

app/setup_handlers.go

Remove modules that are already registered from setup handler
---
I have...
I have...

chore: remove already registered modules from setup handler

---

config.yml
x/leveragelp/keeper/check_pool_health.go
x/leveragelp/keeper/check_pool_health_test.go
x/leveragelp/types/errors.go
x/margin/keeper/check_pool_health.go
x/margin/keeper/check_pool_health_test.go
x/margin/types/errors.go

Closes:
* https://github.com/elys-network/issues/issues/441
Fix margin params.
---
I have...
I have...

fix: margin params

---

app/wasm.go

Closes:
* https://github.com/elys-network/issues/issues/470
---
I have...
I have...

feat: add binding for the oracle asset info message

---

app/wasm.go
x/amm/keeper/query_swap_estimation.go

Closes:
* https://github.com/elys-network/issues/issues/459
Add implementation logic of swap estimation query:
```
$ elysd tx amm create-pool 100uatom,100uusdc 100000000000uatom,100000000000uusdc --swap-fee=0.00 --exit-fee=0.00 --use-oracle=false  --from=treasury --yes --gas=1000000
$ elysd tx amm create-pool 100uelys,100uatom 1000000uatom,100000000000uelys --swap-fee=0.00 --exit-fee=0.00 --use-oracle=false  --from=treasury --yes --gas=1000000         
$ elysd q amm swap-estimation 1000000uelys 1 uatom 2 uusdc
spotPrice: "0.000009000000000000"
tokenOut:
amount: "9"
denom: uusdc
```
---
I have...
_All items are required. Please add a note if the item …

feat: add swap estimation implementation

---

app/app.go
app/wasm.go

Closes:
* https://github.com/elys-network/issues/issues/453
---
I have...
I have...

feat: WASM binding for open and close margin position

---

app/setup_handlers.go

Closes:
* https://github.com/elys-network/issues/issues/496
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only be …

fix: setup handler

---

cmd/elysd/cmd/root.go

Update default timeout commit to 3s to reduce to the overall blocktime from 4s to 3s.
---
I have...
I have... …

feat: reduce blocktime to 3s

---

x/accountedpool/types/query.pb.gw.go
x/amm/types/query.pb.gw.go
x/commitment/client/wasm/messenger.go
x/commitment/keeper/msg_server_cancel_vest.go
x/leveragelp/types/query.pb.gw.go
x/margin/client/wasm/messenger.go

Closes:
* https://github.com/elys-network/issues/issues/484
Denom checking issue with cancel vesting.
---
Original it was using the same denom for finding vesting info and use the same denom for filtering the vesting asset. In a word, we create vesting info using eden but put elys in the specific vesting item. If you use the same denom for all, it won't work.
I have...
I have... …

chore: fix denom checking issue with cancel vest

---

architecture.md

Hello
I fixed a typo in the docs,
Hope it helps.
Br,
Tudor.

fix typo architecture.md

---

app/app.go
wasmbindings/client/register_custom_plugins.go
wasmbindings/externals/auth/messenger.go
wasmbindings/externals/auth/querier.go
wasmbindings/externals/auth/query_accounts.go
wasmbindings/types/custom_message_decorator.go
wasmbindings/types/new_query_plugin.go
wasmbindings/types/types.go

Closes:
* https://github.com/elys-network/issues/issues/519
Add auth query Accounts as wasm bindings
---
I have...
I have... …

feat: add auth queries as wasm bindings

---

x/amm/types/calc_in_amt_given_out.go
x/margin/keeper/begin_blocker_process_mtp.go
x/margin/keeper/calc_mtp_take_profit_liabilities.go
x/margin/keeper/keeper.go
x/margin/keeper/open_long_process.go
x/margin/keeper/open_short_process.go
x/margin/keeper/repay.go
x/margin/types/calc_mtp_consolidate_leverage.go
x/margin/types/calc_mtp_take_profit_custodies.go
x/margin/types/calc_mtp_take_profit_custody.go
x/margin/types/is_take_profit_price_inifite.go
x/margin/types/pool.go
x/margin/types/pool_test.go

Refactor TP calc and update
---
I have...
I have...

refactor: tp calc and update

---

x/amm/keeper/calc_in_route_by_denom.go
x/amm/keeper/calc_in_route_by_denom_test.go
x/amm/keeper/calc_out_route_by_denom.go
x/amm/keeper/calc_out_route_by_denom_test.go
x/amm/keeper/pool.go
x/amm/keeper/pool_test.go
x/amm/keeper/query_in_route_by_denom.go
x/amm/keeper/query_out_route_by_denom.go
x/amm/types/errors.go

Implementation logic for query of in and out route.
---
I have...
I have...

feat: implementation logic for query in and out route

---

x/incentive/migrations/v5_migration.go
x/incentive/module.go
x/leveragelp/migrations/new_migrator.go
x/leveragelp/migrations/v2_migration.go
x/leveragelp/module.go

Add migrators to both leveragelp and incentive as params structure got updated.
---
I have...
I have...

fix: add migrations to both incentive and leveragelp

---

app/app.go

Closes:
---
I have...
I have... …

Fixing AMM & Margin hook issues

---

x/incentive/module.go

Increment incentive module version.
---
I have...
I have...

fix: increment incentive module version

---

x/amm/keeper/apply_discount.go

Check if discount value is nil
---
I have...
I have...

fix: check if discount nil

---

app/setup_handlers.go

* Fix elys/usdc pool weight 
---
I have...
I have...

fix: elys/usdc testnet pool weight

---

x/incentive/client/wasm/messenger.go
x/incentive/keeper/abci.go

---
I have...
I have...
Please provide any relevant …

chore: fix to update incentive info from tokenomics module instantly

---

x/amm/keeper/calc_in_route_by_denom.go
x/amm/keeper/calc_in_route_by_denom_test.go
x/amm/keeper/calc_swap_estimation_by_denom.go

Closes:
* https://github.com/elys-network/issues/issues/565
* https://github.com/elys-network/issues/issues/568
* same denom scenario
* denom out was returning wrong spot price
---
I have...
I have...
Please provide any relevant before and after screenshots by …

fix: denom out scenario and same denoms

---

app/setup_handlers.go

remove unecessary migration logic
---
I have...
I have...

chore: remove unecessary migration logic

---

x/amm/keeper/calc_swap_estimation_by_denom.go
x/amm/keeper/calc_swap_estimation_by_denom_test.go
x/amm/keeper/msg_server_swap_by_denom.go
x/amm/keeper/msg_server_swap_by_denom_test.go
x/amm/keeper/query_swap_estimation_by_denom.go
x/amm/types/expected_keepers.go
x/assetprofile/keeper/entry.go
x/margin/keeper/query_open_estimation.go
x/margin/types/expected_keepers.go
x/margin/types/mocks/amm_keeper.go
x/margin/types/mocks/asset_profile_keeper.go

Closes:
* https://github.com/elys-network/issues/issues/580
* fix price impact calculation
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, demo videos can be highly beneficial in demonstrating …

fix: price impact calculation

---

.github/workflows/release.yml

Closes:
* https://github.com/elys-network/issues/issues/602
Auto deployment of new releases to TestNet
---
I have...
I have... …

ci: auto deployment to testnet workflow

---

.github/workflows/release.yml

Closes:
* https://github.com/elys-network/issues/issues/602
Update upgrade block height.
---
I have...
I have... …

ci: new upgrade block height 2 hrs apart

---

wasmbindings/externals/auth/query_addresses.go
wasmbindings/types/types.go

Closes:
* https://github.com/elys-network/issues/issues/582
Add missing pagination response field to response of query addresses.
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, demo videos can …

fix: add pagination to query addresses response

---

.github/workflows/release.yml

Use dist binaries
---
I have...
I have...

ci: use dist files

---

.github/workflows/release.yml

Fix double quotes
---
I have...
I have...

ci: fix dbl quotes

---

.github/workflows/release.yml

Add helper function to release workflow.
---
I have...
I have...

ci: add helper function to release workflow

---

.github/workflows/release.yml

Add debugging lines to release workflow.
---
I have...
I have...

ci: add debug

---

.github/workflows/release.yml

remove uncessary debug lines
---
I have...
I have...

ci: get rid of debugs

---

.github/workflows/release.yml

Skip validation step as the new release is created a draft and artifact file will only be available when public.
---
I have...
I have... …

ci: skip validator as new release created as draft

---

.goreleaser.yaml

Update go releaser default description for new releases.
---
I have...
I have...

ci: update go releasere default description

---

x/amm/keeper/calc_in_route_spot_price.go
x/amm/keeper/calc_out_route_spot_price.go

fix token out calculation in calc in/out route spot price functions
---
I have...
I have...

fix: calc in/out route spot price

---

x/margin/migrations/v5_migration.go
x/margin/module.go

Add missing margin migrator logic.
---
I have...
I have...

fix: missing margin module migrator logic

---

config.yml
docs/static/openapi.yml
proto/elys/assetprofile/query.proto
scripts/examples/transferhook/mars.yml
wasmbindings/types/types.go
x/assetprofile/client/cli/query.go
x/assetprofile/client/cli/query_entry.go
x/assetprofile/client/wasm/querier.go
x/assetprofile/client/wasm/query_entry_by_denom.go
x/assetprofile/keeper/query_entry.go
x/assetprofile/types/query.pb.go
x/assetprofile/types/query.pb.gw.go
x/margin/types/query.pb.gw.go
x/oracle/types/query.pb.gw.go

Closes:
* https://github.com/elys-network/issues/issues/615
Add get entry by denom query to assetprofile module.
---
I have...
I have... …

feat: add assetprofile show entry by denom query

---

.gitignore
x/margin/keeper/open_consolidate_long.go

Closes:
* https://github.com/elys-network/issues/issues/585
Wrong leverage comparison in open consolidate flow
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, demo videos can be highly beneficial …

fix: consolidate leverage comparision

---

x/margin/client/wasm/msg_close.go
x/margin/client/wasm/msg_open.go

Closes:
* https://github.com/elys-network/issues/issues/585
Add missing fields to responses of msg open and close in wasm bindings
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, demo videos can …

fix: add missing id field to wasm binding margin open/close msgs

---

.goreleaser.yaml

New goreleaser release non-draft
---
I have...
I have...

ci: new release submitted as non-drfat

---

x/amm/keeper/keeper_swap_exact_amount_in.go
x/amm/types/errors.go

"Lesser than" is incorrect since "lesser" and "than" both imply a comparison, which makes them redundant when used together. "less than" is proper.

Grammar correction

---

app/app.go

Increase max wasm sizes
---
I have...
I have...

chore: increase max wasm size

---

scripts/upgrade-assure/update-genesis.go
x/perpetual/keeper/begin_blocker_process_mtp.go

* Error messages should be infos instead
* Update gas limit for localnet clock module
---
I have...
I have... …

fix: error messages are info instead

---

x/perpetual/keeper/begin_blocker_process_mtp.go
x/perpetual/keeper/repay.go

* fix errors in begin blocker perpetual
* fix repay errors
---
I have...
I have...

fix: repay flow errors

---

scripts/upgrade-assure/update-config.go

minor change
---
I have...
I have...

ci: minor fix

---

x/amm/keeper/calc_swap_estimation_by_denom.go
x/incentive/keeper/keeper.go

* Fix incentive module negative amount set to decimal coin.
* Return discount value to swap estimation by denom response
---
I have...
I have... …

fix: negative amount set to decimal coin

---

x/perpetual/keeper/calc_min_collateral.go
x/perpetual/keeper/query_open_estimation.go
x/perpetual/keeper/query_open_estimation_test.go

* Fix minimum collateral amount calculation
```
$ elysd q perpetual open-estimation long 5 uelys 8000000ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65 --take-profit 20
available_liquidity:
amount: "32831933228"
denom: uelys
borrow_interest_rate: "0.000000220000000000"
collateral:
amount: "8000000"
denom: ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65
discount: "0.000000000000000000"
estimated_pnl: "594857427"
funding_rate: "0.000300000000000000"
leverage: "5.000000000000000000"
liquidation_price: "3.928564318593877050"
min_collateral:
amount: "42666666"
denom: ibc/2180E84E20F5679FCC760D8C165B60F42065DEF7F46A72B447CFF1B7DC6C0A65
open_price: "4.128564318593877050"
position: LONG
position_size:
amount: "9688598"
denom: uelys
price_impact: …
```

fix: open estimation min collateral calc

---

scripts/upgrade-assure/types.go

Fix upgrade assure logic
---
I have...
I have...

chore: fix upgrade test logic

---

app/setup_handlers.go

Update the old proposals deletion logic in setup handler
---
I have...
I have...

fix: update old proposals deletion logic in setup handler

---

app/setup_handlers.go

Remove unnecessary code logics from setup handlers
---
I have...
I have...

ci: clean up setup handler

---

scripts/upgrade-assure/export.go
scripts/upgrade-assure/update-genesis.go

* add gov state to software upgrade testing script
---
I have...
I have...

test: add gov proposals state to test software upgrade

---

x/perpetual/keeper/query_open_estimation.go
x/perpetual/keeper/query_open_estimation_test.go

Fix open estimation edge cases
---
I have...
I have...

fix: open estimation edge cases

---

x/perpetual/keeper/open_long_test.go
x/perpetual/keeper/open_short_test.go
x/perpetual/keeper/update_open_price.go

Fix open price update for short positions
---
I have...
I have...

fix: update open price for short positions

---

scripts/upgrade-assure/README.md
scripts/upgrade-assure/retrieve-snapshot.go

Add documentation to use alternative snapshot provider to spin up a localnet.
---
I have...
I have...

docs: update docs to use alternative snapshot provider

---

scripts/upgrade-assure/export.go

Closes:
---
I have...
I have... …

For better error understanding

---

app/ante.go

* Previously the max voting power was defined as percentage
* The following changes update the code to define the max voting power parameter as fractional number from 0 to 1
---
I have...
I have...
Please provide any relevant before and after screenshots by …

fix: replace max voting power from percentage to fractional number

---

x/incentive/keeper/keeper.go

* when oracle price feeder is not ready yet, and price point for base currency expired the eden price in base currency is not available and therefore returns zero, in some parts of the code we are using this rate as denominator which causes a division by zero, those changes prevents that from happening.
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any …

fix: check eden price non zero

---

.github/workflows/release.yml
cmd/elysd/cmd/root.go

Increased the blocktime to 5s
---
I have...
I have...

fix: update timeout commit value to 5s

---

validator.md

increase hardware requirements
Closes:
---
I have...
I have... …

Update hardware requirements

---

cmd/elysd/cmd/root.go

Updating min blocktime back to 3s
---
I have...
I have...

fix: update min blocktime back to 3s

---

.github/workflows/release.yml

Update upgrade height in ci workflow
---
I have...
I have...

ci: update upgrade height

---

readme.md

update readme to include troubleshooting instructions.
---
I have...
I have...

docs: update readme with troubleshooting bits

---

scripts/upgrade-assure/update-config.go

* update upgrade assure to apply rocks db only if using linux os
---
I have...
I have...

chore: update script

---

scripts/upgrade-assure/update-config.go

Update upgrade-assure to use a greater tx broadcast timeout value
---
I have...
I have...

chore: update script to increase timeout broadcast tx commit

---

scripts/upgrade-assure/update-config.go

Closes:
---
I have...
I have... …

chore: update scirpt

---

.goreleaser.yaml

Add missing rocksdb tag to goreleaser config file
---
I have...
I have...

ci: add rocksdb tag to goreleaser

---

scripts/upgrade-assure/add-genesis-account.go
scripts/upgrade-assure/add-key.go
scripts/upgrade-assure/export.go
scripts/upgrade-assure/get-flags.go
scripts/upgrade-assure/retrieve-snapshot.go
scripts/upgrade-assure/update-genesis.go
scripts/upgrade-assure/upgrade-assure.go

Closes:
---
I have...
I have... …

fix: balance invariance issue with upgrade assure

---

.goreleaser.yaml
Makefile

Closes:
* Add rocksdb lib install to goreleaser
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. …

ci: add rocksdb lib install step

---

app/setup_handlers.go
scripts/upgrade-assure/wait-for-node-to-start.go

Decommision deprecated pool 
---
I have...
I have...

chore: decommission deprecated pool

---

scripts/upgrade-assure/update-config.go

Closes:
---
I have...
I have... …

chore: fix sed in scripts

---

app/setup_handlers.go
x/epochs/migrations/v3_migration.go
x/epochs/module.go

* init time value to current start time and start time fields of newly added epoch infos
---
I have...
I have... …

fix: epochs infos missing start time

---

validator.md

Update validator guide to include app.tom file change for the db backend setting
---
I have...
I have...

docs: update validator guide to update app db backend

---

scripts/upgrade-assure/export.go
scripts/upgrade-assure/update-genesis.go
scripts/upgrade-assure/upgrade-assure.go
scripts/upgrade-assure/wait-for-node-to-start.go

Fix upgrade assure issues
---
I have...
I have... …

chore: fix upgrade assure script

---

.github/workflows/software-upgrade-test.yml
scripts/upgrade-assure/README.md
scripts/upgrade-assure/upgrade-assure.go

* Upgrade assure runs chain init using old binary data structure
* Upgrade assure runs software upgrade using new binary data structure
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, demo videos …

ci: upgrade assure run in two stages

---

.github/workflows/software-upgrade-test.yml

Use faster snap server
---
I have...
I have...

ci: use faster snap provider server

---

app/setup_handlers.go

Untomstone both euphoria and shangrila validators in TestNet
---
I have...
I have...

chore: untoumbosted testnet nodes

---

.github/workflows/release.yml
.github/workflows/software-upgrade-test.yml
.github/workflows/test.yml

Test out go version 1.21 with software upgrade test
---
I have...
I have...

ci: use go 1.21

---

.github/workflows/software-upgrade-test.yml
app/setup_handlers.go
scripts/upgrade-assure/check-tx-status.go
scripts/upgrade-assure/export.go
scripts/upgrade-assure/parse-tx-hash.go
scripts/upgrade-assure/submit-upgrade-proposal.go
scripts/upgrade-assure/types.go
scripts/upgrade-assure/upgrade-assure.go
scripts/upgrade-assure/vote-on-upgrade-proposal.go
scripts/upgrade-assure/wait-for-tx-confirmation.go

3 foundation nodes are still "jailed" until an unreachable date.
* unjail nodes
* remove unbonded delegations
* change bonding status
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, demo videos …

chore: fix jailed nodes

---

scripts/upgrade-assure/update-config.go

Deploying AH contract locally is not scalling.

Increase timeout

---

.github/workflows/release.yml

New gov window is `21600` blocks which means 24h on a 4s block time.

Update upgrade gov window

---

x/amm/keeper/calc_in_route_spot_price.go
x/amm/keeper/keeper_swap_exact_amount_in.go
x/amm/keeper/route_exact_amount_in.go

swap fee discounted down to half pool swap fee
---
I have...
I have...

feat: swap fee discount cap to half pool swap fee min

---

x/amm/keeper/keeper_swap_exact_amount_in.go
x/amm/keeper/keeper_swap_exact_amount_in_test.go
x/amm/keeper/keeper_swap_exact_amount_out.go
x/amm/keeper/msg_server_swap_by_denom_test.go
x/amm/keeper/msg_server_swap_exact_amount_in_test.go
x/amm/keeper/route_exact_amount_in_test.go

Apply swap fee to token in/out amount for each hop in a multi hop scenario
---
I have...
I have...

fix: apply swap fee to token in/out amount for each hop in a multi hop scenario

---

scripts/upgrade-assure/README.md
scripts/upgrade-assure/start.go
x/epochs/keeper/abci.go
x/leveragelp/keeper/position_close.go
x/perpetual/keeper/begin_blocker_process_mtp.go

* Replace info by debug loggings in perpetual module
* Add debug mode to upgrade-assure command
---
I have...
I have... …

chore: replace info by debug loggings in perpetual

---

.github/workflows/software-upgrade-test.yml
.github/workflows/test.yml

Trigger test software upgrade CI workflow in the default branch to create a cache that can be used in any pull request.
---
I have...
I have... …

ci: trigger test software upgrade workflow in main

---

.github/workflows/software-upgrade-test.yml

minor fix with head ref variable used for the new snapshot file name
---
I have...
I have...

ci: minor fix with head ref

---

.github/workflows/software-upgrade-test.yml

Instead of caching the home folders for node 1 and 2, we create intermediary backup folders that will persist the state of the elys folders pre-upgrade.
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. …

ci: cache backup folders

---

.github/workflows/software-upgrade-test.yml
cmd/upgrade-assure/backup-genesis-init-file.go
cmd/upgrade-assure/restore-genesis-init-file.go
cmd/upgrade-assure/upgrade-assure.go

If `genesis.json` file is missing in the `.elys/config` folder, the API service fails to start up, this PR solves the issue by restoring the init genesis.json file.
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them …

ci: fix api service issue

---

.github/workflows/software-upgrade-test.yml

Remove date time from snapshot file name
---
I have...
I have...

ci: update snapshot name

---

.github/workflows/software-upgrade-test.yml

reduce mem limit for upgrade step as it hits the runner resource limit otherwise
---
I have...
I have...

ci: reduce mem limit for upgrade step

---

.github/workflows/software-upgrade-test.yml

Use diff snapshot
---
I have...
I have...

ci: use diff snapshot

---

.github/workflows/software-upgrade-test.yml

use faster snapshot url
---
I have...
I have...

ci: use faster snapshot url

---

.github/workflows/software-upgrade-test.yml

Restore old cache
---
I have...
I have...

ci: restore old cache

---

.github/workflows/software-upgrade-test.yml

Fix cache key
---
I have...
I have...

ci: fix cache key

---

.github/workflows/software-upgrade-test.yml

Restore genesis json
---
I have...
I have...

ci: restore genesis json

---

.github/workflows/software-upgrade-test.yml

Fix cp genesis json
---
I have...
I have...

ci: fix cp genesis json

---

.github/workflows/software-upgrade-test.yml

use elys runner
---
I have...
I have...

ci: use elys runner

---

.github/workflows/software-upgrade-test.yml

Cache save always flag enabled
---
I have...
I have...

ci: cache save always

---

.github/workflows/software-upgrade-test.yml

Split workflow into 2 separate jobs
---
I have...
I have...

ci: split workflow into 2 jobs

---

.github/workflows/software-upgrade-test.yml

Reduce mem limit
---
I have...
I have...

ci: reduce mem limit

---

.github/workflows/software-upgrade-test.yml

reduce mem limit to 8GB
---
I have...
I have...

ci: reduce mem limit to 8

---

.github/workflows/delete-branch-snapshot.yml

Fix github ref
---
I have...
I have...

ci: fix github ref

---

.github/workflows/delete-branch-snapshot.yml

Use event ref
---
I have...
I have...

ci: use event ref

---

app/setup_handlers.go

* We fixed a migration issue with `x/distribution`. In version 3, the module transitioned away from `x/params`, moving the parameter states to the module state.
* We addressed a balance mismatch in the `x/distribution` module that occurred because a previously removed module was reintroduced without resetting the module balance.
* These issues were not detected during our LocalNet software upgrade testing, which you can review https://github.com/elys-network/elys/actions/runs/9157713440/job/25176012920#step:7:78, because the `distribution` module state was not exported from the TestNet snapshot as it was not previously used in the chain. :tired_face:
---
please add links to any relevant follow up …

fix: distribution module param migration + reset module balance

---

.github/workflows/software-upgrade-test.yml

Fix setup go cache 
---
I have...
I have...

ci: fix setup go cache

---

.github/workflows/software-upgrade-test.yml
cmd/upgrade-assure/export.go
cmd/upgrade-assure/types.go
cmd/upgrade-assure/update-genesis.go

Fix upgrade assure
---
I have...
I have...

ci: fix upgrade-assure

---

.github/workflows/software-upgrade-test.yml

Reduce go mem limit in upgrade-assure
---
I have...
I have...

ci: reduce go mem limit

---

.github/workflows/software-upgrade-test.yml

disable go cache in create second validator job
---
I have...
I have...

ci: create second val job without go cache

---

.github/workflows/software-upgrade-test.yml

Closes:
---
I have...
I have... …

ci: compile new upgrade assure binary

---

.github/workflows/software-upgrade-test.yml

Closes:
---
I have...
I have... …

ci: add build step in prepare val data

---

.github/workflows/software-upgrade-test.yml

Closes:
---
I have...
I have... …

ci: build binary in next steps

---

cmd/upgrade-assure/types.go

Closes:
---
I have...
I have... …

ci: add new modules types

---

cmd/upgrade-assure/update-genesis.go

Closes:
---
I have...
I have... …

ci: update dist balanace in upgrade-assure

---

.github/workflows/software-upgrade-test.yml

Closes:
---
I have...
I have... …

ci: fix build old binary job

---

.github/workflows/software-upgrade-test.yml

Closes:
---
I have...
I have... …

ci: fix action checkout

---

.github/workflows/software-upgrade-test.yml

Closes:
---
I have...
I have... …

ci: fix cache

---

.github/workflows/software-upgrade-test.yml

Closes:
---
I have...
I have... …

ci: use new upgrade assure binary

---

.github/workflows/software-upgrade-test.yml

Closes:
---
I have...
I have... …

ci: fix go cache

---

.github/workflows/software-upgrade-test.yml

Closes:
---
I have...
I have... …

ci: restore tmp folder and fix paths

---

cmd/upgrade-assure/update-genesis.go

Closes:
---
I have...
I have... …

ci: fix distr balance

---

cmd/upgrade-assure/update-genesis.go

Closes:
---
I have...
I have... …

ci: fix distr balance second attempt

---

cmd/upgrade-assure/update-genesis.go

Closes:
---
I have...
I have... …

ci: fix distr balance state 3

---

cmd/upgrade-assure/update-genesis.go

Closes:
---
I have...
I have... …

ci: fix dist balance 4

---

.github/workflows/software-upgrade-test.yml

Closes:
---
I have...
I have... …

ci: align mem limit in CI

---

.github/workflows/release.yml

Closes:
---
I have...
I have... …

ci: reduce upgrade height to 5h

---

proto/elys/estaking/tx.proto
x/estaking/types/tx.pb.go

make struct comments match struct names
---
I have...
I have... …

chore: make struct comments match struct names

---

x/transferhook/spec/01_concepts.md
x/transferhook/spec/02_usage.md
x/transferhook/spec/03_keeper.md
x/transferhook/spec/04_protobuf_definitions.md
x/transferhook/spec/05_functions.md
x/transferhook/spec/README.md

Add transferhook module documentation
---
I have...
I have...

docs: add transferhook module specs

---

x/oracle/spec/01_concepts.md
x/oracle/spec/02_usage.md
x/oracle/spec/03_keeper.md
x/oracle/spec/04_protobuf_definitions.md
x/oracle/spec/05_functions.md
x/oracle/spec/README.md

Add the oracle module spec docs
---
I have...
I have...

docs: add oracle specs

---

x/leveragelp/keeper/utils.go

In existing implementation, existing leverage doesn't account for collateral and amm pool id, also traversing all the positions is not desirable
---
I have...
I have... …

[Leverage LP] Fix: Get existing leverage position

---

x/accountedpool/spec/01_concepts.md
x/accountedpool/spec/02_usage.md
x/accountedpool/spec/03_keeper.md
x/accountedpool/spec/04_protobuf_definitions.md
x/accountedpool/spec/05_functions.md
x/accountedpool/spec/README.md

Add accounted pool module specs
---
I have...
I have...

docs: add accounted pool module specs

---

x/commitment/spec/01_concepts.md
x/commitment/spec/02_usage.md
x/commitment/spec/03_keeper.md
x/commitment/spec/04_protobuf_definitions.md
x/commitment/spec/05_functions.md
x/commitment/spec/README.md

Add commitment module specs
---
I have...
I have...

docs: add commitment module specs

---

x/stablestake/spec/01_concepts.md
x/stablestake/spec/02_usage.md
x/stablestake/spec/03_keeper.md
x/stablestake/spec/04_protobuf_definitions.md
x/stablestake/spec/05_functions.md
x/stablestake/spec/README.md

Add stablestake module specs
---
I have...
I have...

docs: add stablestake module specs

---

x/amm/types/pool_calc_join_pool_shares.go
x/clock/keeper/querier.go

make function comment match function names
---
I have...
I have... …

chore: make function comment match function names

---

x/tier/keeper/portfolio.go
x/tier/keeper/portfolio_test.go
x/tier/types/expected_keepers.go

Closes:
Bug fix: Calculate discount
Use denom instead of base denom in asset entry
---
I have...
I have...
Please provide any relevant before and after …

[Bug]: Fix calculate discount and add more tests

---

x/accountedpool/types/query.pb.gw.go
x/amm/types/query.pb.gw.go
x/assetprofile/types/query.pb.gw.go
x/burner/types/query.pb.gw.go
x/clock/types/query.pb.gw.go
x/commitment/types/query.pb.gw.go
x/epochs/types/query.pb.gw.go
x/estaking/types/query.pb.gw.go
x/incentive/types/query.pb.gw.go
x/leveragelp/types/query.pb.gw.go
x/masterchef/types/query.pb.gw.go
x/oracle/types/query.pb.gw.go
x/parameter/types/query.pb.gw.go
x/perpetual/types/query.pb.gw.go
x/stablestake/types/query.pb.gw.go
x/tier/types/query.pb.gw.go
x/tokenomics/types/query.pb.gw.go
x/transferhook/types/query.pb.gw.go

Closes:
---
I have...
I have... …

fix: regen proto files

---

.github/workflows/deploy.yml

a new step was added to backup devnet chain

a new step was added to backup devnet chain

---

.github/workflows/devnet-branch-protection.yml
.github/workflows/main-branch-protection.yml

Protect `main` and `devnet` branches from getting merges from wrong branches
---
I have...
I have...

ci: branch protection ci workflows

---

x/leveragelp/keeper/position_close.go

fix leveragelp close
Closes:
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, …

Leveragelp fixes (#610)

---

.github/workflows/rollback.yml

New workflow was added to rollback  devnet to old version

New workflow was added to rollback  devnet to old version

---

x/leveragelp/keeper/position_close.go
x/leveragelp/types/errors.go
x/stablestake/keeper/debt.go
x/stablestake/types/errors.go

* fix leveragelp close
* add lpTokenPrice query
* fix leveragelp close
Closes:
---
I have...
I have...
Are there any specific considerations to take into account when deploying …

Leveragelp close position update fix (#615)

---

x/perpetual/keeper/add_collateral.go

Added missing hook argument 
---
I have...
I have...

fix: missing hook arg

---

.github/workflows/delete-branch-snapshot.yml
.github/workflows/software-upgrade-test.yml
x/stablestake/keeper/debt.go
x/stablestake/types/errors.go

For security reasons, we should avoid borrowing more than 90% in total to the stablestake pool.
Add check for the same
---
I have...
I have... …

Max borrow amount

---

.github/workflows/software-upgrade-test.yml

Fix lookup cache flow issue
---
I have...
I have...

ci: fix lookup cache issue

---

x/leveragelp/keeper/position_close.go
x/leveragelp/migrations/v6_migration.go
x/leveragelp/module.go

- There was negative lp amount because we were subtracting the lp amount 2 times from pool
- Fix bug
---
I have...
I have... …

[Leveragelp]: Bug fix

---

.github/workflows/deploy.yml

command timeout was added to backup devnet step

command timeout was added to backup devnet step

---

x/leveragelp/keeper/add_collateral.go
x/leveragelp/keeper/position.go
x/leveragelp/keeper/position_close.go
x/leveragelp/types/errors.go

- Claim rewards before closing
---
I have...
I have... …

[Leveragelp]: Claim rewards before closing

---

x/stablestake/keeper/debt.go
x/stablestake/keeper/debt_test.go

- Update interest paid
---
I have...
I have...
Please …

[StableStake]: Update interest paid

---

x/leveragelp/keeper/position.go

Throw error when asset price not set in leverage lp keeper position query
---
I have...
I have...

fix: throw error if asset price not set in leverage lp keeper position

---

app/setup_handlers.go

* remove old CW codes (binaries) to save space
* remove AH CW contract states entirely as we migrated all AH functionalities to Tier native module
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, …

ci: setup handler to clean up old states

---

x/tier/keeper/portfolio.go
x/tier/types/expected_keepers.go

- Migrate remaining functionnalities from AH CW to Tier native module
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only …

Migrate remaining functionalities from AH CW to Tier native module

---

x/leveragelp/types/hooks.go

fix some comments for struct field
Closes:
---
I have...
I have... …

chore: fix some comments for struct field

---

app/setup_handlers.go

Update setup handler
---
I have...
I have...

ci: update setup handler

---

app/ante/validator_tx_fee.go

Remove min gas prices logs
---
I have...
I have...

fix: remove min gas price logs

---

app/app.go
app/setup_handlers.go
proto/elys/stablestake/tx.proto
testutil/keeper/stablestake.go
x/leveragelp/spec/07_pool_status.md
x/leveragelp/spec/README.md
x/perpetual/spec/07_pool_status.md
x/perpetual/spec/README.md
x/stablestake/keeper/keeper.go
x/stablestake/keeper/msg_server_update_params.go
x/stablestake/types/codec.go
x/stablestake/types/message_update_params.go
x/stablestake/types/message_update_params_test.go
x/stablestake/types/tx.pb.go

Add `MsgUpdateParams` message to the `StableStake` module
Tests:
Before update params proposal:
```
$ elysd q stablestake params --output json | jq
{
"params": {
"deposit_denom": "uusdc",
"redemption_rate": "1.000000000000000000",
"epoch_length": "1",
"interest_rate": "0.150000000000000000",
"interest_rate_max": "0.170000000000000000",
"interest_rate_min": "0.120000000000000000",
"interest_rate_increase": "0.010000000000000000",
"interest_rate_decrease": "0.010000000000000000",
"health_gain_factor": "1.000000000000000000",
"total_value": "0"
}
}
```
Proposal:
```
{
"title": "Update stablestake params",
"summary": "Update stablestake params",
"messages": [
{
"@type": "/elys.stablestake.MsgUpdateParams",
"authority": "elys10d07y265gmmuvt4z0w9aw880jnsr700j6z2zm3",
"params": { …
```

feat: add update params message to stablestake

---

x/leveragelp/keeper/position.go

- Fix `asset not found`
---
I have...
I have...
Please …

[Leveragelp]: Fix `asset not found`

---

app/setup_handlers.go

* Remove both AH and FS contract states and addresses
---
I have...
I have...

ci: setup handler: remove AH and FS CW states

---

x/perpetual/spec/README.md

Fixed the link in [x/perpetual/spec/README.md](https://github.com/elys-network/elys/blob/main/x/perpetual/spec/README.md) from:
```
2. **[Mechanisms](02_mechanisms.md)**
```
to:
```
2. **[Mechanisms](02_mechanism.md)**
```
Corrected a path to a file within the documentation.
---
I have...
I have...
There are no special deployment notes needed for this documentation fix.

docs: fix broken link in README.md

---

x/leveragelp/types/keys.go

-  Increase pagination limit
---
I have...
I have... …

Increase pagination limit

---

app/setup_handlers.go

Closes:
---
I have...
I have... …

chore: replace info by debug logs in setup handler

---

.github/workflows/delete-branch-snapshot.yml
.github/workflows/software-upgrade-test.yml
app/setup_handlers.go

Use latest snap gen version
---
I have...
I have...

ci: update snap gen version

---

x/leveragelp/spec/bot.md
x/leveragelp/types/keys.go

- Add bot documentation and architecture
- Increase pagination limit
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only …

Add bot documentation and architecture

---

x/amm/keeper/apply_exit_pool_state_change.go
x/amm/keeper/apply_exit_pool_state_change_test.go
x/amm/keeper/keeper_exit_pool.go
x/amm/keeper/msg_server_exit_pool.go
x/amm/keeper/query_exit_pool_estimation.go
x/leveragelp/keeper/begin_blocker_test.go
x/leveragelp/keeper/hooks_amm.go
x/leveragelp/keeper/keeper_test.go
x/leveragelp/keeper/msg_server_close_test.go
x/leveragelp/keeper/position.go
x/leveragelp/keeper/position_close.go
x/leveragelp/keeper/position_close_test.go
x/leveragelp/keeper/position_open_test.go
x/leveragelp/keeper/utils_test.go
x/leveragelp/types/expected_keepers.go
x/masterchef/keeper/hooks_masterchef_test.go

This PR fixes the closing position for a non-zero exit fee pool. The issue happens because exitFee is not considered when calculating userAmount.

Fixing close position for non-zero exit fee pool

---

x/tier/keeper/portfolio.go

Closes:
---
I have...
I have... …

[Bug]: incorrect commitments due to usdc price

---

x/amm/types/codec.go
x/assetprofile/types/codec.go
x/burner/types/codec.go
x/commitment/types/codec.go
x/estaking/types/codec.go
x/leveragelp/types/codec.go
x/masterchef/types/codec.go
x/oracle/types/codec.go
x/parameter/types/codec.go
x/perpetual/types/codec.go
x/stablestake/types/codec.go
x/tier/types/codec.go
x/tokenomics/types/codec.go

Every module should be compatible with amino signer: https://trello.com/c/dvjncVdg/385-add-ledger-connection

Fix modules codecs

---

x/leveragelp/keeper/position_close.go
x/leveragelp/keeper/position_close_test.go

- Fix repayment to avoid position liquidation failure
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only be evaluated in …

[Bug]: Position liquidation failure

---

app/setup_handlers.go

Due to breaking changes on gov proposal messages, previous proposals below id 258 are not compatible anymore, those changes deleted those past proposals in TestNet.
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them …

ci: fix gov proposals in testnet

---

x/tier/keeper/portfolio.go
x/tier/types/expected_keepers.go

- Fix
---
I have...
I have...
Please provide any …

[Bug]: Consider eden price for vesting amount

---

app/setup_handlers.go

Updating setup handler version to apply gov proposals listing fix to correct software upgrade version.
---
I have...
I have... …

ci: update setup handler version

---

.github/workflows/delete-branch-snapshot.yml
.github/workflows/software-upgrade-test.yml

Closes:
---
I have...
I have... …

ci: snap gen version update

---

.github/workflows/delete-branch-snapshot.yml
.github/workflows/software-upgrade-test.yml

Refresh snapshot upload output 
---
I have...
I have...

ci: refresh upload snapshot output

---

x/commitment/keeper/msg_server_uncommit_tokens_test.go
x/commitment/migrations/v4_migration.go
x/commitment/module.go
x/commitment/types/commitments.go
x/estaking/keeper/keeper_burn_edenB_test.go
x/incentive/keeper/keeper.go
x/masterchef/keeper/abci.go
x/masterchef/keeper/hooks_masterchef.go
x/masterchef/keeper/keeper.go
x/masterchef/keeper/msg_server.go

Closes:
https://trello.com/c/gVx08BX6/482-zero-balance
Remove commitment when amount is zero
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, demo videos can be highly beneficial in demonstrating …

feat: remove zero value commitment tokens

---

x/leveragelp/keeper/add_collateral.go
x/leveragelp/keeper/begin_blocker_test.go
x/leveragelp/keeper/position.go
x/leveragelp/keeper/position_close.go
x/leveragelp/keeper/position_close_test.go
x/leveragelp/keeper/query_estimation.go
x/leveragelp/keeper/query_position.go
x/leveragelp/types/expected_keepers.go
x/stablestake/keeper/debt.go
x/stablestake/keeper/debt_test.go
x/tier/keeper/portfolio.go
x/tier/types/expected_keepers.go

- Improve Getter and Setter for Debt
---
I have...
I have... …

Improve Getter and Setter for Debt

---

app/setup_handlers.go

Document process to update setup handle version and migration logic
---
I have...
I have...

ci: minor setup handler changes

---

.github/workflows/deploy.yml

Closes:
---
I have...
I have... …

command timeout was increased to 60m

---

readme.md

Add localnet setup guide to readme
---
I have...
I have...

docs: add localnet setup guide to readme

---

x/commitment/migrations/v4_migration.go

- Fix migration
---
I have...
I have...
Please provide …

[Bug]: Commitment migration

---

x/commitment/migrations/v4_migration.go

- Fix claim > vestedSoFar
---
I have...
I have... …

[Data]: Commitment module fix

---

x/accountedpool/keeper/hooks_perpetual.go
x/amm/types/hooks.go
x/burner/keeper/epoch_hooks.go
x/commitment/keeper/epoch_hooks.go
x/epochs/keeper/hooks.go
x/epochs/types/interfaces.go
x/leveragelp/keeper/hooks_amm.go
x/leveragelp/keeper/hooks_epoch.go
x/masterchef/keeper/hooks_amm.go
x/oracle/keeper/hooks.go
x/perpetual/keeper/hooks_amm.go
x/perpetual/keeper/hooks_epoch.go
x/perpetual/types/hooks.go
x/tier/keeper/hooks_amm.go
x/tier/keeper/hooks_perpetual.go

Closes:
---
I have...
I have... …

feat: add error handling on hooks

---

x/leveragelp/spec/incentivized_liquidation_system_spec.md

Write up for leverage lp liquidation system v2 that includes the rewards and penalty program.
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, demo videos can be highly beneficial in demonstrating …

docs: liq system v2 spec for leverage lp

---

x/masterchef/keeper/abci.go
x/masterchef/spec/01_concepts.md
x/masterchef/spec/03_keeper.md

Closes:
---
I have...
I have... …

[Masterchef]: Spec improvements

---

x/orderbook/spec/README.md

Orderbook module specifications
---
I have...
I have...

docs: orderbook specs

---

x/epochs/spec/05_hooks.md

recieve -> receive
---
I have...
I have...
Please …

docs: update 05_hooks.md

---

.github/workflows/release.yml

Reduced upgrade time window to 1 hour temporary for the fix upgrade.
---
I have...
I have...

ci: reduce upgrade time window to one hour temporaly for the fix upgrade

---

.github/workflows/release.yml

Restore 5-hour upgrade time window for the future upgrades.
---
I have...
I have...

ci: restore 5 hrs upgrade time window

---

.github/workflows/delete-branch-snapshot.yml
.github/workflows/software-upgrade-test.yml

Attempt to enable commitment module data within snap gen
---
I have...
I have...

ci: enable commitment data within snap gen

---

.github/workflows/delete-branch-snapshot.yml
.github/workflows/software-upgrade-test.yml

Enable stablestake module data within snap gen flow
---
I have...
I have...

ci: enable stable stake data

---

x/leveragelp/keeper/position.go

Closes:
---
I have...
I have... …

[LeverageLp]: Fix position query

---

.github/workflows/software-upgrade-test.yml

Attempt to produce localnet snapshot with stablestake data
---
I have...
I have...

ci: stablestake data export flow using new binary

---

x/perpetual/spec/07_pool_status.md
x/perpetual/spec/08_borrow_interest_payment.md
x/perpetual/spec/09_funding_payment.md
x/perpetual/spec/09_funding_rate_payment.md
x/perpetual/spec/README.md

Add documentation about funding rate payment mechanism for perpetual.
---
I have...
I have...

docs: funding rate payment

---

x/perpetual/spec/bot.md
x/perpetual/spec/incentivized_liquidation_system.md

- Add bot and incentivised spec
---
I have...
I have... …

[Perpetual]: Add bot and incentivised spec

---

x/stablestake/keeper/begin_blocker.go
x/stablestake/keeper/debt.go
x/stablestake/migrations/v3_migration.go
x/stablestake/migrations/v4_migration.go
x/stablestake/migrations/v5_migration.go
x/stablestake/module.go

Closes:
---
I have...
I have... …

Fix: Negative leveragelp

---

x/leveragelp/keeper/position_open.go
x/leveragelp/types/msgs.go

Remaining changes required for fixing issue with leverage one
---
I have...
I have...

fix: remaining changes needed for leverage one fix

---

.github/workflows/release.yml
app/setup_handlers.go

Reduce software upgrade window to 1 hour
---
I have...
I have...

ci: software upgrade after an hour

---

x/leveragelp/types/msgs.go
x/leveragelp/types/msgs_test.go

Fix Leverage LP unit test
---
I have...
I have...

test: fix leveragelp unit tests

---

.github/workflows/delete-branch-snapshot.yml
.github/workflows/release.yml
.github/workflows/software-upgrade-test.yml
app/setup_handlers.go

* fix broken gov proposals queries on TestNet
* move back to 5 hours upgrade window
* bump snap gen version
---
I have...
I have... …

ci: fix gov proposals

---

.github/workflows/delete-branch-snapshot.yml
.github/workflows/software-upgrade-test.yml

New version of snap gen that includes new tradeshield native module data
---
I have...
I have...

ci: bump snap gen version

---

codecov.yml

Closes:
---
I have...
I have... …

Add tradeshield in codecov

---

x/leveragelp/keeper/query_estimation.go
x/leveragelp/keeper/query_estimation_test.go

- Leverage LP wrong closing values
---
I have...
I have... …

[LeverageLp]: CloseEst bug fix

---

.github/workflows/release.yml

Update upgrade window
---
I have...
I have...

ci: update upgrade window

---

x/tradeshield/types/codec.go

- Add init to codec
---
I have...
I have...
Please …

[Tradeshield]: Add init to codec

---

x/tradeshield/spec/bot.md

* add bots spec to tradeshield module
---
I have...
I have...

docs(tradeshield): add bots doc

---

x/perpetual/keeper/estimate_and_repay.go
x/perpetual/keeper/process_mtp.go
x/perpetual/keeper/settle_funding_fee_collection.go
x/perpetual/keeper/update_mtp_health.go

- Handle cases when custody becomes negative
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only be evaluated in a …

[Perpetual]: Cannot liquidate positions

---

x/perpetual/migrations/v10_migration.go
x/perpetual/types/params.go

Update funding fee base rate to apply 0.03% / hour
---
I have...
I have...

fix(perpetual): apply funding fee base rate to hourly

---

x/perpetual/migrations/v10_migration.go
x/tradeshield/client/cli/query_pending_perpetual_order_for_address.go
x/tradeshield/client/cli/query_pending_spot_order_for_address.go

1. Fix status query, here are the results
```
ay@Amits-MBP ~ % elysd q tradeshield pending-perpetual-order-for-address valid_address                  
pending_perpetual_orders:
- borrow_interest_rate: "1.000000000000000000"
collateral:
amount: "10"
denom: denom
funding_rate: "1.000000000000000000"
leverage: "1.000000000000000000"
liquidation_price: "1.000000000000000000"
order_id: "1"
owner_address: valid_address
perpetual_order_type: LIMITCLOSE
position: LONG
position_id: "1"
position_size:
amount: "10"
denom: denom
status: PENDING
stop_loss_price: "1.000000000000000000"
take_profit_price: "1.000000000000000000"
trading_asset: asset
trigger_price:
base_denom: base
quote_denom: quote
rate: "1.000000000000000000"
- borrow_interest_rate: "1.000000000000000000"
collateral:
amount: "10" …
```

Fix status query and add const setting of params

---

x/perpetual/keeper/get_net_open_interest.go

- Fix open interest
- Net open interest should always be in terms of trading asset
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects …

[Perpetual]: Fix open interest

---

x/perpetual/keeper/mtp.go

- NewCoin function will result in error if pnl negative, use coin{} instead
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can …

[Pereptual]: Fix

---

x/masterchef/keeper/abci_test.go
x/masterchef/keeper/external_incentive_test.go

- Add tests for external incentive distribution
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only be evaluated in a …

[Masterchef]: Tests

---

x/commitment/keeper/keeper_test.go
x/commitment/keeper/msg_server_cancel_vest_test.go
x/commitment/keeper/msg_server_commit_claimed_rewards_test.go

* improve commitment keeper function test coverage to 81%
---
I have...
I have...

test(commitment): improve code coverage to 81%

---

x/amm/keeper/abci.go
x/amm/keeper/calc_in_route_spot_price.go
x/amm/keeper/calc_out_route_spot_price.go
x/amm/keeper/create_elys_multihop_expected_swap_outs.go
x/amm/keeper/create_multihop_expected_swap_outs.go
x/amm/keeper/estimate_price.go
x/amm/keeper/fee.go
x/amm/keeper/keeper_join_pool_no_swap.go
x/amm/keeper/keeper_swap_exact_amount_in.go
x/amm/keeper/keeper_swap_exact_amount_out.go
x/amm/keeper/msg_server_feed_multiple_external_liquidity.go
x/amm/keeper/pool.go
x/amm/keeper/query_join_pool_estimation.go
x/amm/types/calc_in_amt_given_out.go
x/amm/types/calc_out_amt_given_in.go
x/amm/types/swap_in_amt_given_out.go
x/amm/types/swap_out_amt_given_in.go
x/leveragelp/keeper/keeper.go
x/leveragelp/types/expected_keepers.go
x/masterchef/keeper/abci.go
x/masterchef/types/expected_keepers.go
x/perpetual/keeper/estimate_swap.go
x/perpetual/types/expected_keepers.go

Closes:
---
I have...
I have... …

[Amm]: Impact and weight field fixes

---

x/tradeshield/keeper/msg_server_spot_order.go
x/tradeshield/migrations/v5_migrator.go
x/tradeshield/module.go

- Fix missing fields
---
I have...
I have...
Please …

[Tradeshield]: Fix missing fields

---

x/perpetual/keeper/check_same_asset_position.go
x/tradeshield/keeper/msg_server_perpetual_order.go
x/tradeshield/keeper/msg_server_spot_order.go
x/tradeshield/keeper/pending_spot_order.go
x/tradeshield/keeper/pending_spot_order_test.go
x/tradeshield/types/codec.go

- Do error handling
- Standardize message
- Edge case conditions fixes
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only …

[Tradeshield]: Review fixes/changes

---

app/setup_handlers.go

- To ensure coverage for a 14-day unbonding period, set EvidenceParams.MaxAgeNumBlocks and EvidenceParams.MaxAgeDuration.
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts …

Halborn finding: ASA-2024-004: Default evidence configuration parameters may limit window of validity

---

.github/workflows/delete-branch-snapshot.yml
.github/workflows/software-upgrade-test.yml
x/tradeshield/spec/bot.md

Closes:
---
I have...
I have... …

[Tradeshield]: Update doc

---

.goreleaser.yaml

* set goreleaser version in config file
---
I have...
I have...

ci: set version to goreleaser

---

scripts/examples/wasm/wasm.sh
x/amm/keeper/abci_test.go
x/amm/keeper/apply_exit_pool_state_change_test.go
x/amm/keeper/calc_in_route_spot_price_test.go
x/amm/keeper/calc_out_route_spot_price_test.go
x/amm/keeper/calc_swap_estimation_by_denom_test.go
x/amm/keeper/fee_test.go
x/amm/keeper/keeper_swap_exact_amount_in_test.go
x/amm/keeper/keeper_swap_exact_amount_out_test.go
x/amm/keeper/keeper_test.go
x/amm/keeper/msg_server_create_pool_test.go
x/amm/keeper/msg_server_exit_pool_test.go
x/amm/keeper/msg_server_feed_multiple_external_liquidity_test.go
x/amm/keeper/msg_server_join_pool_test.go
x/amm/keeper/msg_server_swap_by_denom_test.go
x/amm/keeper/msg_server_swap_exact_amount_in_test.go
x/amm/keeper/msg_server_swap_exact_amount_out_test.go
x/amm/keeper/msg_server_update_pool_params_test.go
x/amm/keeper/oracle_pool_slippage_track_test.go
x/amm/keeper/route_exact_amount_in_test.go
x/amm/keeper/route_exact_amount_out_test.go
x/amm/keeper/update_pool_for_swap_test.go
x/estaking/keeper/hooks_staking_test.go
x/estaking/keeper/keeper_test.go
x/perpetual/keeper/keeper_test.go

test(amm): increase test coverage

---

.github/workflows/release.yml

* use previous binary version to raise proposal in release CI workflow
---
I have...
I have...

ci: use previous version to raise proposal

---

app/setup_handlers.go

* module store removal already remove all the module store keys no need to double down with loop over each key
---
I have...
I have... …

fix: v0.50.0 patch1

---

x/tier/keeper/portfolio.go

- Fix usdc conversion
---
I have...
I have...
Please …

[Tier]: Fix usdc conversion

---

.github/workflows/release.yml

* use new software upgrade tx command in CI release workflow
* use new binary for raising and voting proposal
---
I have...
I have...
Please provide any relevant before and after screenshots by uploading them here. Additionally, demo videos can be highly beneficial …

ci: use new software upgrade tx cmd in release workflow

---

.github/workflows/delete-branch-snapshot.yml
.github/workflows/software-upgrade-test.yml

* use latest binary version
---
I have...
I have...

ci: use latest binary version

---

x/tradeshield/keeper/msg_server_execute_orders.go
x/tradeshield/keeper/msg_server_perpetual_order.go
x/tradeshield/keeper/pending_perpetual_order.go
x/tradeshield/types/events.go

- Handle error and improve execution logs
---
I have...
I have... …

[Tradeshield]: Handle error and improve execution logs

---

app/keepers/keepers.go
testutil/keeper/commitment.go
x/commitment/keeper/keeper.go
x/commitment/keeper/msg_server_stake.go

- Do not allow vested tokens to be staked
```
ay@Amits-MBP ~ % elysd q bank spendable-balances elys1eue9d00xv6v9zv22k2q6uxpmv5ulp6jaryuge0
balances:
- amount: "79"
denom: uelys
pagination:
total: "1"
ay@Amits-MBP ~ % elysd tx commitment stake 10000 uelys elysvaloper1dd34v384hdfqgajkg0jzp0y5k6qlvhltr73as2  --from=elys1eue9d00xv6v9zv22k2q6uxpmv5ulp6jaryuge0 --gas=4000000
auth_info:
fee:
amount: []
gas_limit: "4000000"
granter: ""
payer: ""
signer_infos: []
tip: null
body:
extension_options: []
memo: ""
messages:
- '@type': /elys.commitment.MsgStake
amount: "10000"
asset: uelys
creator: elys1eue9d00xv6v9zv22k2q6uxpmv5ulp6jaryuge0
validator_address: elysvaloper1dd34v384hdfqgajkg0jzp0y5k6qlvhltr73as2
non_critical_extension_options: []
timeout_height: "0"
signatures: []
confirm transaction …
```

[Commitment]: Do not allow vested tokens to be staked

---

codecov.yml

- Ignore pulsar files
---
I have...
I have...
Please …

Ignore pulsar files

---

x/tradeshield/keeper/keeper_test.go
x/tradeshield/keeper/msg_server_execute_order_test.go
x/tradeshield/keeper/msg_server_perpetual_order_test.go
x/tradeshield/keeper/msg_server_spot_order_test.go
x/tradeshield/keeper/msg_server_update_params_test.go

Closes:
---
I have...
I have... …

Add Tradeshield module tests

---

x/amm/keeper/msg_server_feed_multiple_external_liquidity.go
x/amm/keeper/msg_server_feed_multiple_external_liquidity_test.go
x/tradeshield/keeper/pending_spot_order.go
x/tradeshield/types/errors.go

- Avoid tx when market price is zero, remove price from external liquidity 
- Verified for trade, add liquidity
---
I have...
I have... …

Avoid tx when market price is zero, remove price from external liquidity 

---

x/tradeshield/keeper/msg_server_perpetual_order.go
x/tradeshield/keeper/msg_server_test.go
x/tradeshield/types/expected_keepers.go
x/tradeshield/types/mocks/perpetual_keeper.go

Closes:
---
I have...
I have... …

Add check in UpdatePerpetualOrder

---

x/perpetual/keeper/query_open_estimation.go

Closes:
---
I have...
I have... …

fix query open estimation in perpetual module

---

app/setup_handlers.go

* fix jailed validators untombstoning logic
---
I have...
I have...

fix: jailed validators

---

.github/workflows/software-upgrade-test.yml
x/estaking/keeper/abci_test.go
x/estaking/keeper/keeper.go
x/estaking/keeper/keeper_test.go
x/estaking/keeper/query_test.go
x/estaking/keeper/reward_test.go
x/estaking/modules/distribution/module.go

- Reward distribution fixes
- Add tests
---
I have...
I have... …

[Estaking]: Reward distribution fixes

---

x/estaking/keeper/abci.go

- Change EdenB mint amount
---
I have...
I have... …

[Estaking]: Change EdenB mint amount

---

Makefile
chains.yaml

Closes:
---
I have...
I have... …

added static link option

---

.github/workflows/software-upgrade-test.yml

Closes:
---
I have...
I have... …

ci: use new runner id

---

x/README.md
x/burner/spec/README.md
x/tier/spec/README.md

* add a summary doc to the `x` folder that describes all Elys modules and link them to their individual module spec doc.
---
I have...
I have... …

docs: add x modules summary doc

---

x/amm/keeper/keeper_swap_exact_amount_in.go
x/amm/keeper/keeper_swap_exact_amount_out.go

Closes:
---
I have...
I have... …

Error handling

---

x/leveragelp/keeper/pool.go
x/perpetual/keeper/pool.go
x/perpetual/types/calc_funding_rate.go
x/tradeshield/keeper/pending_spot_order.go

fix some function names in comment
---
I have...
I have... …

chore: fix some function names in comment

---

x/amm/client/cli/tx_swap_by_denom.go
x/amm/keeper/msg_server_swap_by_denom.go
x/tradeshield/client/cli/tx_spot_order.go
x/tradeshield/keeper/msg_server_spot_order.go
x/tradeshield/types/expected_keepers.go

- Updated `CmdSwapByDenom` to set default values for minimum and maximum amounts if not provided.
- Changed the response in `SwapByDenom` to return the correct denomination for the amount.
- Modified `CancelSpotOrder` to return all available balances to the owner instead of just the order amount.
- Added `GetAllBalances` method to the `BankKeeper` interface for balance retrieval.
These changes improve the usability of the swap command and ensure proper balance management in spot order cancellations.
---
I have...
your handle next to the items reviewed if you only …

Fix swap command and enhance balance handling

---

.github/workflows/release.yml

- Re-enabled the software upgrade proposal creation in the GitHub Actions workflow.
---
I have...
I have... …

Update release workflow to enable software upgrade proposal creation

---

x/tradeshield/keeper/pending_spot_order.go

fix comment
Closes:
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts …

chore: fix comment

---

.github/workflows/devnet-deploy.yml
.github/workflows/mainnet-deploy.yml
.github/workflows/release-and-testnet-deploy.yml
app/setup_handlers.go

- Added a MainNet deployment workflow that retrieves the latest release version and creates a software upgrade proposal.
---
I have...
I have... …

Add deployment workflow for MainNet

---

.github/workflows/mainnet-deploy.yml
.github/workflows/release-and-testnet-deploy.yml
cmd/elysd/cmd/upgrade.go

- Updated the MainNet and TestNet deployment workflows to download the latest binary and SHA256 checksum from GitHub.
- Modified the software upgrade proposal command to accept an expedited parameter, allowing for faster proposal processing.
- Improved checksum retrieval by using the downloaded SHA256 file instead of a hardcoded path.
- Adjusted key import commands to streamline the process for multiple proposers.
---
I have...
I have...
Are there any specific considerations to take into …

Support expedited voting period in CI deployment workflow

---

.github/workflows/mainnet-deploy.yml
.github/workflows/release-and-testnet-deploy.yml

* use correct keyring for CI deployment workflows
---
I have...
I have...

ci: use correct keyring backend deployment

---

x/amm/types/pool.go
x/amm/types/utils.go
x/burner/spec/02_state.md
x/commitment/keeper/msg_server_vest.go
x/epochs/spec/05_hooks.md
x/estaking/modules/distribution/module.go
x/tradeshield/keeper/msg_server_perpetual_order_test.go
x/transferhook/module_ibc.go

fix some typos and function names in comment
Closes:
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may …

chore: fix some typos and function names in comment

---

app/setup_handlers.go

update version in setup handler
---
I have...
I have...

chore: update version

---

.github/workflows/mainnet-deploy-2h.yml
.github/workflows/mainnet-deploy-48h.yml

Update mainnet deploy CI workflows
---
I have...
I have...

ci: update mainnet deploy workflows

---

.github/workflows/mainnet-deploy-2h.yml
.github/workflows/mainnet-deploy-48h.yml

Update buffer time for ci workflow deploy to networks
---
I have...
I have...

ci: update buffer time for deployment workflows

---

.github/workflows/test-software-upgrade-and-create-new-snapshot.yml

Applied URL for testnet and mainnet
---
I have...
I have...

ci: use mainnet applied endpoint

---

x/estaking/keeper/hooks.go

- Added claim rewards function before commitment is changed
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only be …

[Bug]: Claim rewards when commitment is changed

---

x/leveragelp/keeper/msg_server_close_positions.go
x/perpetual/keeper/msg_server_close_positions.go
x/tradeshield/keeper/msg_server_execute_orders.go

- Buy orders error handling
---
I have...
I have... …

Buy orders error handling

---

.github/workflows/create-release.yml
.github/workflows/mainnet-deploy-2h.yml
.github/workflows/mainnet-deploy-48h.yml
.github/workflows/test-software-upgrade-and-create-new-snapshot.yml
.github/workflows/testnet-deploy-2h.yml
.github/workflows/testnet-deploy-48h.yml
app/setup_handlers.go
readme.md
x/amm/client/cli/query_denom_liquidity_test.go

* split testnet deployment and release CI workflows
* use version.Version in setup handler

ci: split testnet and release CI workflows

---

.github/workflows/test-software-upgrade-and-create-new-snapshot.yml

* internal snapshots are not pruned and execeed 60+ GB
* instead use of high stakes snapshots that are less than 500 MB
---
I have...
I have... …

ci: use highstakes snapshots

---

x/accountedpool/keeper/accounted_pool.go

Fix wrong comment
---
I have...
I have...
Please …

Fix wrong comment

---

x/amm/types/calc_exit_pool.go
x/amm/types/pool_join_pool.go

Closes:
---
I have...
I have... …

Reduce recovery reward and return value

---

x/stablestake/keeper/interest_rate.go

Closes:
---
I have...
I have... …

Update interest computation formula

---

x/tradeshield/keeper/pending_spot_order.go

Closes:
---
I have...
I have... …

Fix limit price

---

x/leveragelp/keeper/msg_server_claim_rewards.go
x/leveragelp/keeper/msg_server_open.go
x/leveragelp/keeper/msg_server_update_stop_loss.go
x/leveragelp/types/events.go

Closes:
---
I have...
I have... …

Add trigger

---

x/amm/types/weight_fees.go

Closes:
---
I have...
I have... …

change initial to final weight

---

x/stablestake/client/cli/tx.go
x/stablestake/client/cli/tx_add_pool.go
x/stablestake/types/message_add_pool.go
x/stablestake/types/message_add_pool_test.go

Closes:
---
I have...
I have... …

[Stablestake]: Add command line

---

x/stablestake/keeper/interest_rate.go
x/stablestake/keeper/interest_rate_test.go
x/stablestake/keeper/msg_server_unbond.go
x/stablestake/keeper/msg_server_unbond_test.go
x/stablestake/types/errors.go

Closes:
---
I have...
I have... …

stablestake fixes

---

x/leveragelp/keeper/position_open.go

Closes:
---
I have...
I have... …

Leveragelp remove check

---

x/amm/keeper/calc_in_route_spot_price.go
x/amm/keeper/calc_out_route_spot_price.go
x/amm/keeper/keeper_swap_exact_amount_in.go
x/amm/keeper/keeper_swap_exact_amount_in_test.go
x/amm/keeper/keeper_swap_exact_amount_out.go
x/amm/keeper/keeper_swap_exact_amount_out_test.go
x/amm/keeper/route_exact_amount_in.go
x/amm/keeper/route_exact_amount_out.go
x/amm/keeper/swap_in_amt_given_out.go
x/amm/keeper/swap_out_amt_given_in.go
x/amm/migrations/v12_migration.go
x/masterchef/keeper/abci.go
x/masterchef/types/expected_keepers.go
x/perpetual/keeper/estimate_swap.go
x/perpetual/types/expected_keepers.go

Closes:
---
I have...
I have... …

Taker fee routes and change min slippage

---

app/oracle.go
go.mod
go.sum

- Ojo was upgraded.
- TIA,SAGA, and NTRN pairs  were updated on migration.

Ojo upgrade

---

x/stablestake/keeper/msg_server_unbond.go
x/stablestake/keeper/params.go
x/stablestake/migrations/v9_migration.go

Closes:
---
I have...
I have... …

Stablestake migration for testnet denom

---

.goreleaser.yaml
Makefile

Closes:
---
I have...
I have... …

Update goreleaser config and Makefile for cosmwasm

---

x/amm/keeper/query_swap_estimation_by_denom.go

Closes:
---
I have...
I have... …

Fix swap estimation by denom query

---

x/stablestake/keeper/debt.go

Closes:
---
I have...
I have... …

Migration fixes

---

x/stablestake/keeper/pool.go

fix function name in comment
---
I have...
I have... …

chore: fix function name in comment

---

x/masterchef/keeper/query_chain_tvl.go
x/masterchef/types/expected_keepers.go

Closes:
---
I have...
I have... …

Update chain tvl query for expanded stablestake vaults

---

x/amm/keeper/apply_join_pool_state_change.go
x/amm/keeper/keeper_join_pool_no_swap.go
x/amm/keeper/query_join_pool_estimation.go

Closes:
---
I have...
I have... …

Weight rewards fix

---

x/masterchef/keeper/abci.go
x/masterchef/keeper/abci_test.go
x/masterchef/module.go

Closes:
---
I have...
I have... …

[Bug]: move taker fees to begin block

---

codecov.yml
scripts/test_scripts/masterchef/query.sh
x/masterchef/keeper/keeper.go

fix some typos in comment
Closes:
---
I have...
I have... …

chore: fix some typos in comment

---

x/amm/keeper/params.go
x/leveragelp/keeper/msg_server_open.go
x/perpetual/keeper/msg_server_open.go
x/tradeshield/types/message_execute_orders.go
x/tradeshield/types/messages_pending_perpetual_order.go
x/tradeshield/types/messages_pending_spot_order.go

There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
Closes:
---
I have...
your handle next to the items reviewed if you only reviewed selected …

refactor: use slices.Contains to simplify code

---

cmd/elysd/cmd/root.go

Adds simulation command to tx, it is already a part of comsos-sdk.
It is easier to debug for users as `dry-run` command asks for priv-key to be present in keyring.
Adds a simulate command, no big changes.
---
I have...
- [ x ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ x ] added `!` to the type prefix if API or client breaking change
- [ x ] followed …

feat: add simulate command

---

x/amm/keeper/calc_in_route_spot_price.go
x/amm/keeper/calc_out_route_spot_price.go
x/amm/keeper/query_swap_estimation_by_denom.go

Closes:
---
I have...
I have... …

[Amm]: Query fixes

---

x/tradeshield/keeper/msg_server_execute_order_test.go
x/tradeshield/keeper/pending_spot_order.go

Closes:
---
I have...
I have... …

[Tradeshield]: Fix batch execution issue

---

x/amm/keeper/update_pool_for_swap.go

Closes:
---
I have...
I have... …

Fix slippage tracking

---

x/perpetual/keeper/borrow_rate_test.go
x/perpetual/keeper/pool.go

Closes:
---
I have...
I have... …

[Perps]: Fix rate formula

---

x/commitment/keeper/keeper.go
x/estaking/keeper/abci.go

Closes:
---
I have...
I have... …

fix allocations in estaking

---

x/leveragelp/keeper/pool.go
x/leveragelp/migrations/v21_migration.go
x/leveragelp/module.go

Closes:
---
I have...
I have... …

LeverageLp total migration

---

x/perpetual/keeper/estimate_and_repay.go
x/perpetual/keeper/keeper.go
x/perpetual/keeper/process_open.go
x/perpetual/types/expected_keepers.go

Closes:
---
I have...
I have... …

Track via amm

---

x/amm/types/mocks/oracle_keeper.go
x/perpetual/keeper/close.go
x/perpetual/keeper/close_position.go
x/perpetual/keeper/estimate_and_repay.go
x/perpetual/keeper/events.go
x/perpetual/keeper/force_close.go
x/perpetual/keeper/force_close_test.go
x/perpetual/keeper/msg_server_add_collateral.go
x/perpetual/keeper/msg_server_update_stop_loss.go
x/perpetual/keeper/msg_server_update_take_profit_price.go
x/perpetual/keeper/mtp_trigger.go
x/perpetual/keeper/mtp_trigger_test.go
x/perpetual/keeper/open_consolidate.go
x/perpetual/keeper/process_mtp.go
x/perpetual/keeper/query_close_estimation.go

Closes:
---
I have...
I have... …

[Perpetual]: Add closing price [at execution]

---

x/perpetual/keeper/msg_server_close_positions.go
x/perpetual/types/events.go

Closes:
---
I have...
I have... …

[Perpetual]: Add events in perpetual close positions message

---

x/amm/keeper/pool.go
x/amm/types/pool_calc_join_pool_shares.go

make function comments match function names
---
I have...
I have... …

chore: make function comments match function names

---

x/perpetual/spec/02_mechanism.md

remove redundant word in x/perpetual/spec/02_mechanism.md
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only be evaluated …

chore: remove redundant word in x/perpetual/spec/02_mechanism.md
