elys-network/elys

x/commitment/keeper/epoch_hooks.go, x/commitment/keeper/vest.go
Removes a leftover TODO and pulls epochIdentifier from VestingInfo param. 
Removes leftover testing logs.
Manual test results:
```
~/elys$ elysd tx commitment vest 1000 ueden --from treasury
~/elys$ elysd q commitment show-commitments elys12tzylat4udvjj56uuhu3vj2n4vgp7cf9fwna9w
commitments:
committed_tokens:
- amount: "1000"
denom: ueden
creator: elys12tzylat4udvjj56uuhu3vj2n4vgp7cf9fwna9w
uncommitted_tokens:
- amount: "98000"
denom: ueden
vesting_tokens:
- current_epoch: "0"
denom: uelys
epoch_identifier: tenseconds
num_epochs: "10"
total_amount: "1000"
unvested_amount: "1000"
~/elys$ elysd q bank balances elys12tzylat4udvjj56uuhu3vj2n4vgp7cf9fwna9w
balances:
- amount: "100000000"
denom: stake
- amount: "99900000"
denom: ueden
- amount: "9000000000000100"
denom: uelys
pagination: …
```
=> Fix: Vesting epoch logic from param

Makefile
The `make build` and `make install` commands are selecting the wrong tag when multiple tags annotate the same commit hash. This results in an incorrect version number being used (e.g., selecting the `latest` tag instead of `v0.3.1`).
To resolve this issue, a pattern was added to the `make` commands to select the correct tag based on its name. This ensures that the correct version number is used in the build and installation process. As a result, the `make` commands now use the correct tag with the version information.
This PR also includes the `v` prefix to use in the displayed version.
=> chore: 🤖 fix conflicting latest tag

x/incentive/keeper/validator.go
- Urgently fix to remove panic when its historical reference count is 0.
=> fix: remove panic when it is 0 reference count

x/amm/keeper/create_elys_multihop_expected_swap_outs.go, x/amm/keeper/msg_server_swap_exact_amount_in_test.go, x/amm/keeper/msg_server_swap_exact_amount_out_test.go, x/amm/keeper/route_exact_amount_in.go, x/amm/keeper/route_exact_amount_out.go
- Handle panic case on RouteExactAmountIn && RouteExactAmountOut on multihop routed for zero division
- Fix zero division case on createElysMultihopExpectedSwapOuts
- Update MsgServerSwapExactAmountIn test to handle multihop case and invalid route case
- Update MsgServerSwapExactAmountOut test to handle multihop case and invalid route case
=> Swap edge case tests & fix panics on swap

app/app.go
=> fix: temp fix to work with version w/ and w/o v prefix

scripts/testing/setup_localnet_nodes.sh
Closes:
* https://github.com/elys-network/issues/issues/355
Fix localnet testing script
---
I have...
I have... …
=> test: fix localnet testing script

x/amm/types/query.pb.gw.go, x/margin/keeper/check_long_assets.go, x/margin/keeper/check_long_assets_test.go, x/margin/keeper/check_short_assets.go, x/margin/keeper/check_short_assets_test.go, x/margin/keeper/open.go, x/margin/keeper/open_long_process.go, x/margin/keeper/open_short_process.go, x/margin/keeper/open_test.go, x/margin/types/expected_keepers.go, x/margin/types/mocks/open_checker.go, x/margin/types/mocks/open_long_checker.go
Refactored additional functions to work with short flow
---
I have...
I have...
=> refactor: margin functions

config.yml, x/amm/client/cli/tx_create_pool.go, x/amm/client/cli/tx_exit_pool.go, x/amm/client/cli/tx_join_pool.go, x/amm/client/cli/tx_swap_exact_amount_in.go, x/amm/client/cli/tx_swap_exact_amount_out.go, x/margin/client/cli/tx_close.go, x/margin/client/cli/tx_close_test.go, x/margin/client/cli/tx_open.go, x/margin/client/cli/tx_open_test.go
Closes:
* https://github.com/elys-network/issues/issues/414
Update margin CLI api to align with other modules structure
---
I have...
I have... …
=> feat: update margin CLI api and add CLI examples

config.yml, docs/static/openapi.yml, x/incentive/keeper/keeper_lps.go
When TVL proxy is zero it is causing a div by zero error within incentive abci.
---
I have...
I have...
=> fix: fix incentive abci division by zero error

app/setup_handlers.go, config.yml, docs/static/openapi.yml, x/accountedpool/types/query.pb.gw.go, x/commitment/types/query.pb.gw.go
* add temporary fix to set the authority values to timebased inflation entries in tokenomics module
---
I have...
I have... …
=> fix: set missing authority value

scripts/upgrade-assure/update-genesis.go, x/amm/keeper/elys_routed_multihop.go, x/amm/keeper/route_exact_amount_in.go
Fix multi hops swap request with recipient address
---
I have...
I have...
=> fix: multi hops swap with recipient

scripts/examples/assetprofile/generate_gov_proposal_payload.sh, scripts/examples/oracle/generate_gov_proposal_payload.sh, scripts/examples/pricefeeder/generate_price_feeder_config.sh, scripts/upgrade-assure/add-genesis-account.go, scripts/upgrade-assure/update-genesis.go, x/amm/client/cli/tx_update_pool_params.go
* fix amm cli update pool params
* add scripts to generate gov proposal payloads
---
I have...
I have...
=> fix: amm cli + add scripts to generate gov proposal payloads

app/setup_handlers.go, scripts/upgrade-assure/submit-upgrade-proposal.go, scripts/upgrade-assure/update-genesis.go, scripts/upgrade-assure/upgrade-assure.go, scripts/upgrade-assure/vote-on-upgrade-proposal.go, scripts/upgrade-assure/wait-for-next-block.go, scripts/upgrade-assure/wait-for-tx-confirmation.go
Remove old gov proposals that breaks the commitment refactoring new data structure
---
I have...
I have... …
=> fix: delete old proposals breaking commitment refactoring

.github/workflows/delete-branch-snapshot.yml, .github/workflows/software-upgrade-test.yml, Makefile, cmd/delete-snapshot/main.go, cmd/upgrade-assure/update-genesis.go
Delete branch snapshot when branch is deleted
---
I have...
I have...
=> ci: delete branch snapshot

x/estaking/spec/01_concepts.md, x/estaking/spec/02_usage.md, x/estaking/spec/03_keeper.md, x/estaking/spec/04_protobuf_definitions.md, x/estaking/spec/05_functions.md, x/estaking/spec/README.md
Add specs for the estaking module
---
I have...
I have...
=> docs: estaking spec folder

x/accountedpool/spec/01_concepts.md
Added concept content to Accounted Pool module
---
I have...
I have...
=> docs: accounted pool module concept doc

x/leveragelp/keeper/position_open.go, x/leveragelp/types/errors.go
- Leverage should be same for existing positions
- Add leverage check
---
I have...
I have...
=> [Leveragelp]: Leverage should be same for existing positions

x/leveragelp/spec/incentivized_liquidation_system.md, x/leveragelp/spec/incentivized_liquidation_system_spec.md
- Add spec for discussion
---
I have...
I have... …
=> Incentivized Liquidation System for Leverage and Perpetual Market

x/amm/types/constants.go, x/amm/types/pow.go, x/amm/types/pow_approx.go, x/amm/types/pow_approx_test.go
It adds a new function `PowerApproximation` which can calculate power on numbers greater than 2 as well.
The previous function `PowApprox` had that limitation.
The previous function didn't work because `term.MulMut(c).MulMut(x).QuoMut(bigK)` becomes too large for sdk.Dec to store as max allowed number of bits are 315 and max value should be  < 2^256
Closes:
* https://github.com/elys-network/issues/issues/669
=> Adding PowerApproximation function

x/incentive/keeper/apr.go, x/masterchef/keeper/abci.go, x/masterchef/keeper/apr_stable_stake.go
Pool APR value’s growing as time goes due to issue in UpdateAmmPoolAPR function on chain side.
Closes:
* https://trello.com/c/S0ETSMB0/344-pool-apr-is-wrong
apr in query is recalculated and for some reason it is being multiplied by 100 (probably to show in percent) , but where the values are being stored it is stored in decimal points , updated the querys to show decimal points instead of percent
---
I have...
I have...
Are there any specific considerations to take into account when …
=> fix: pool apr

x/masterchef/keeper/abci.go
Mitigate Panic error in leveragelp/ABCI caused by must acc account function
---
I have...
I have...
=> fix: mitigate panic caused by must acc address in abci

x/perpetual/keeper/keeper_test.go, x/perpetual/keeper/process_mtp.go
=> fix: stop loss triggering logic

app/app.go, testutil/keeper/masterchef.go, x/masterchef/keeper/abci.go, x/masterchef/keeper/abci_test.go, x/masterchef/keeper/keeper.go, x/masterchef/types/expected_keepers.go, x/perpetual/keeper/keeper.go
- Add perpetual fee collection function in Masterchef
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only be evaluated in …
=> [Perpetual/Masterchef]: Add perpetual fee collection function in Masterchef

x/stablestake/keeper/begin_blocker.go, x/stablestake/keeper/debt.go, x/stablestake/migrations/v6_migration.go, x/stablestake/module.go
- USDC earn amount was off and borrow-ratio amount too
- After debugging it was found that this data was corrupted during a data migration issue(inflated interest issue)
- This PR removes inflated interest and set it to 17%
- Before fix
```
11:23AM INF Total Borrow module=server totalBorrow=1009871895909
11:23AM INF Total Value module=server totalValue=10390564962795
```
- After upgrade and fix
```
12:05PM INF Total Borrow module=server totalBorrow=1009871895909
12:05PM INF Total Value module=server totalValue=3929812980773
```
- There were 396 corrupted debt positions.
---
_All …
=> [Stablestake]: Fix USDC earn amount and borrow ratio

x/perpetual/keeper/mtp.go, x/perpetual/migrations/v10_migration.go, x/perpetual/types/params.go
Fix funding rate range to apply (-)0.1% / hour
---
I have...
I have...
=> fix(perpetual): funding rate range

x/perpetual/client/cli/tx_update_stop_loss.go, x/perpetual/client/cli/tx_update_take_profit_price.go
perpetual tx (update-stop-loss and update-take-profit-price) was showing wrong input ordering
=> fix cli command use statement for perpetual module

.github/workflows/software-upgrade-test.yml, x/estaking/keeper/query.go, x/estaking/types/expected_keepers.go
* issues spotted on new TestNet that was causing swaps and bot close positions transactions to fail due to invalid delegations in commitment module
* PR prevents invalid delegations from going through the reward process
---
I have...
I have...
Please provide any …
=> fix(estaking): prevent reward to invalid delegations

x/leveragelp/client/cli/tx_add_pool.go, x/leveragelp/client/cli/tx_close_positions.go, x/perpetual/client/cli/tx_close_positions.go, x/tradeshield/client/cli/tx_perpetual_order_test.go, x/tradeshield/client/cli/tx_spot_order.go, x/tradeshield/client/cli/tx_spot_order_test.go
remove deprecated of package io/ioutil
=> remove deprecated of package io/ioutil

x/amm/types/genesis.go, x/amm/types/message_feed_multiple_external_liquidity.go, x/amm/types/message_swap_by_denom.go, x/amm/types/params.go, x/amm/types/pool.go
use errors.New to replace fmt.Errorf with no parameters
=> chore: use errors.New to replace fmt.Errorf with no parameters

x/masterchef/keeper/abci.go, x/masterchef/keeper/abci_test.go, x/perpetual/keeper/close_test.go, x/perpetual/keeper/mtp_borrow_interest.go
Closes:
---
I have...
I have... …
=> Perpetual fees should stay in pool

x/amm/keeper/msg_server_join_pool_test.go, x/amm/types/pool_join_pool.go
- Single sided liquidity add breaking/recovery
---
I have...
I have...
Are there any specific considerations to take into account when deploying these changes? This may include new dependencies, scripts that need to be executed, or any aspects that can only be evaluated in a …
=> Single sided liquidity add breaking/recovery

go.mod, go.sum
It's the same bug with the OM denom.
https://github.com/ojo-network/ojo/commit/244234cd4161b9bebe4661dca48cee6ee4d7a85a
=> Fix grpc exchange rate query
